version: "3.1"
services:
  nginx:
    image: "nginx"
    volumes:
      - "${ROOT}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${ROOT}/nginx/proxy.conf:/etc/nginx/proxy.conf"
      - "${ROOT}/nginx/logs:/var/log/nginx"
    ports:
        - "80:80"
    networks:
      - aspnetcoreapp-network

  app:
    build: .
    expose:
        - "80"
    volumes:
      - "${ROOT}/app/logs:/app/logs"
    networks:
      - aspnetcoreapp-network
    ports:
      - "5000:80"

networks:
  aspnetcoreapp-network:
    driver: bridge