version: "3.1"
services:
  nginx:
    build:
      context: "./nginx"
      dockerfile: Dockerfile
    volumes:
      - "${ROOT}/nginx/logs:/var/log/nginx"
    ports:
        - "80:80"
        - "88:88"
    networks:
      - aspnetcoreapp-network

  app:
    build:
      context: "./src"
      dockerfile: Dockerfile
    volumes:
      - "${ROOT}/app/logs:/app/logs"
    networks:
      - aspnetcoreapp-network
    # ports:
      # - "5000:5000"

networks:
  aspnetcoreapp-network:
    driver: bridge