version: "3.1"
services:
  nginx:
    image: "nginx"
    environment:
      - NGINX_HOST=foobar.com
    volumes:
      - "${ROOT}/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
        - "80:80"
    networks:
      - aspnetcoreapp-network

  app:
    build: .
    volumes:
      - "${ROOT}/logs:/app/logs"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge